using KurrentDB.Client;
using Microsoft.Extensions.Logging;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi;
using Shared.Authorisation;
using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using Shared.Serialisation;

namespace MessagingService.Bootstrapper
{
    using Common;
    using Lamar;
    using Microsoft.AspNetCore.Authentication.JwtBearer;
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Diagnostics.HealthChecks;
    using OpenIddict.Validation.AspNetCore;
    using Shared.EventStore.Extensions;
    using Shared.General;
    using Shared.Middleware;
    using Swashbuckle.AspNetCore.Filters;
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.IO;
    using System.Net.Http;

    [ExcludeFromCodeCoverage]
    public class MiddlewareRegistry : ServiceRegistry
    {
        internal String GetSecurityConfigSetting(String settingName) => ConfigurationReader.GetValue("SecurityConfiguration", settingName);

        public MiddlewareRegistry() {
            
            String connectionString = Startup.Configuration.GetValue<String>("EventStoreSettings:ConnectionString");
            KurrentDBClientSettings eventStoreConnectionSettings = KurrentDBClientSettings.Create(connectionString);

            this.AddHealthChecks()
                .AddEventStore(eventStoreConnectionSettings,
                               name: "Eventstore",
                               failureStatus: HealthStatus.Unhealthy,
                               tags: new string[] { "db", "eventstore" });


            this.AddControllers();
            this.ConfigureAuthentication();
            this.ConfigureSwagger();

            bool logRequests = ConfigurationReader.GetValueOrDefault<Boolean>("MiddlewareLogging", "LogRequests", true);
            bool logResponses = ConfigurationReader.GetValueOrDefault<Boolean>("MiddlewareLogging", "LogResponses", true);
            LogLevel middlewareLogLevel = ConfigurationReader.GetValueOrDefault<LogLevel>("MiddlewareLogging", "MiddlewareLogLevel", LogLevel.Warning);

            RequestResponseMiddlewareLoggingConfig config = new(middlewareLogLevel, logRequests, logResponses);

            this.AddSingleton(config);

            this.ConfigureHttpJsonOptions(jsonOptions => JsonSerializerConfiguration.ConfigureMinimalApi(jsonOptions.SerializerOptions));
        }

        private void ConfigureAuthentication() {
            this.AddAuthentication(options =>
            {
                options.DefaultScheme = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme;
            });

            this.AddOpenIddict()
                .AddValidation(options =>
                {
                    // Same as your Authority
                    options.SetIssuer(new Uri(GetSecurityConfigSetting("Authority")));

                    // Enables discovery and HTTP backchannel support
                    options.UseSystemNetHttp()
                        .ConfigureHttpClientHandler(handler =>
                        {
                            // DEV ONLY: bypass all certificate errors
                            handler.ServerCertificateCustomValidationCallback =
                                HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
                        });

                    // Register the ASP.NET Core integration
                    options.UseAspNetCore();

                    // Optionally set expected audience(s):
                    options.AddAudiences(GetSecurityConfigSetting("ApiName"));

                });

            this.AddAuthorization();


            this.AddClientCredentialsOnlyPolicy();
            this.AddClientCredentialsHandler();

            //this.ConfigureHttpJsonOptions(options =>
            //{
            //    options.SerializerOptions.PropertyNamingPolicy = new SnakeCaseNamingPolicy();
            //    options.SerializerOptions.PropertyNameCaseInsensitive = true; // optional, but safer
            //});
        }
        private void ConfigureSwagger() {
            
            this.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo
                {
                    Title = "Messaging API",
                    Version = "1.0",
                    Description = "A REST Api to manage sending of various messages over different formats, currently only Email and SMS are supported.",
                    Contact = new OpenApiContact
                    {
                        Name = "Stuart Ferguson",
                        Email = "golfhandicapping@btinternet.com"
                    }
                });
                // add a custom operation filter which sets default values
                c.OperationFilter<SwaggerDefaultValues>();
                c.ExampleFilters();

                //Locate the XML files being generated by ASP.NET...
                var directory = new DirectoryInfo(AppContext.BaseDirectory);
                var xmlFiles = directory.GetFiles("*.xml");

                //... and tell Swagger to use those XML comments.
                foreach (FileInfo fileInfo in xmlFiles)
                {
                    c.IncludeXmlComments(fileInfo.FullName);
                }
            });

            this.AddSwaggerExamplesFromAssemblyOf<SwaggerJsonConverter>();
        }
    }
}

public static class JsonSerializerConfiguration
{
    public static void ConfigureMinimalApi(JsonSerializerOptions serializerOptions)
    {
        var defaultOptions = SystemTextJsonSerializer.GetDefaultJsonSerializerOptions();
        serializerOptions.PropertyNamingPolicy = defaultOptions.PropertyNamingPolicy;
        serializerOptions.DictionaryKeyPolicy = defaultOptions.DictionaryKeyPolicy;
        serializerOptions.ReferenceHandler = defaultOptions.ReferenceHandler;
        serializerOptions.WriteIndented = defaultOptions.WriteIndented;
        serializerOptions.Converters.Add(new UtcDateTimeJsonConverter());
        serializerOptions.Converters.Add(new NullableUtcDateTimeJsonConverter());
        
    }

    private sealed class UtcDateTimeJsonConverter : System.Text.Json.Serialization.JsonConverter<DateTime>
    {
        public override DateTime Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetDateTime();
            return value.Kind == DateTimeKind.Utc ? value : value.ToUniversalTime();
        }

        public override void Write(Utf8JsonWriter writer, DateTime value, JsonSerializerOptions options)
        {
            writer.WriteStringValue(value.Kind == DateTimeKind.Utc ? value : value.ToUniversalTime());
        }
    }

    private sealed class NullableUtcDateTimeJsonConverter : System.Text.Json.Serialization.JsonConverter<DateTime?>
    {
        public override DateTime? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.Null)
            {
                return null;
            }

            var value = reader.GetDateTime();
            return value.Kind == DateTimeKind.Utc ? value : value.ToUniversalTime();
        }

        public override void Write(Utf8JsonWriter writer, DateTime? value, JsonSerializerOptions options)
        {
            if (value.HasValue == false)
            {
                writer.WriteNullValue();
                return;
            }

            writer.WriteStringValue(value.Value.Kind == DateTimeKind.Utc ? value.Value : value.Value.ToUniversalTime());
        }
    }
}
