name: Code Coverage

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  code-quality: write

jobs:
  build:
    name: Code Coverage
    env:
      ASPNETCORE_ENVIRONMENT: Production

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore Nuget Packages
        run: dotnet restore MessagingService.sln --source ${{ secrets.PUBLICFEEDURL }} --source ${{ secrets.PRIVATEFEED_URL }}

      - name: Build Code
        run: dotnet build MessagingService.sln --configuration Release --no-restore

      - name: Run Unit Tests
        run: |
          echo "ASPNETCORE_ENVIRONMENT are > ${ASPNETCORE_ENVIRONMENT}"
          dotnet test "MessagingService.BusinessLogic.Tests/MessagingService.BusinessLogic.Tests.csproj" --configuration Release /maxcpucount:1 /p:CollectCoverage=true /p:Exclude="[xunit*]*" /p:ExcludeByAttribute="Obsolete" /p:ExcludeByAttribute="GeneratedCodeAttribute" /p:ExcludeByAttribute="CompilerGeneratedAttribute" /p:ExcludeByAttribute="ExcludeFromCodeCoverageAttribute" /p:CoverletOutput="../coverage/businesslogic/" /p:CoverletOutputFormat="cobertura"
          dotnet test "MessagingService.EmailAggregate.Tests/MessagingService.EmailAggregate.Tests.csproj" --configuration Release /maxcpucount:1 /p:CollectCoverage=true /p:Exclude="[xunit*]*" /p:ExcludeByAttribute="Obsolete" /p:ExcludeByAttribute="GeneratedCodeAttribute" /p:ExcludeByAttribute="CompilerGeneratedAttribute" /p:ExcludeByAttribute="ExcludeFromCodeCoverageAttribute" /p:CoverletOutput="../coverage/emailaggregate/" /p:CoverletOutputFormat="cobertura"
          dotnet test "MessagingService.SMSAggregate.Tests/MessagingService.SMSAggregate.Tests.csproj" --configuration Release /maxcpucount:1 /p:CollectCoverage=true /p:Exclude="[xunit*]*" /p:ExcludeByAttribute="Obsolete" /p:ExcludeByAttribute="GeneratedCodeAttribute" /p:ExcludeByAttribute="CompilerGeneratedAttribute" /p:ExcludeByAttribute="ExcludeFromCodeCoverageAttribute" /p:CoverletOutput="../coverage/smsaggregate/" /p:CoverletOutputFormat="cobertura"
          #dotnet test "MessagingService.Tests/MessagingService.Tests.csproj" --configuration Release /maxcpucount:1 /p:CollectCoverage=true /p:Exclude="[xunit*]*" /p:ExcludeByAttribute="Obsolete" /p:ExcludeByAttribute="GeneratedCodeAttribute" /p:ExcludeByAttribute="CompilerGeneratedAttribute" /p:ExcludeByAttribute="ExcludeFromCodeCoverageAttribute" /p:CoverletOutput="../coverage/tests/" /p:CoverletOutputFormat="cobertura"

      - name: Merge Coverage Reports
        uses: danielpalme/ReportGenerator-GitHub-Action@v5
        with:
          reports: ./coverage/**/*.cobertura.xml
          targetdir: ./coverage-report
          reporttypes: Cobertura

      - name: Upload coverage report
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/upload-code-coverage@v1
        with:
          file: ./coverage-report/Cobertura.xml
          language: C#
          label: code-coverage/messagingservice
